
WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v4.02).


WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v4.02).


WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v4.02).

2023-06-02 00:37:18,652:INFO:mapsims:Parsing configuration from common.toml, co_co3.toml
2023-06-02 00:37:18,679:INFO:mapsims:Nside: 4096, Modeling Nside: 2048, Ellmax: 5120
2023-06-02 00:37:18,680:INFO:mapsims:Initializing the PySM Sky object
2023-06-02 00:37:18,681:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/HFI_CompMap_CO-Type1_2048_R2.00_ring.fits
2023-06-02 00:37:18,681:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/HFI_CompMap_CO-Type1_2048_R2.00_ring.fits
2023-06-02 00:37:35,436:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/psimap_dust90_2048.fits
2023-06-02 00:37:35,437:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/psimap_dust90_2048.fits
2023-06-02 00:37:47,482:WARNING:pysm3:No physical unit associated with file /mnt/sdceph/users/azonca/pysm-data/co/psimap_dust90_2048.fits
2023-06-02 00:37:47,483:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/gmap_dust90_2048.fits
2023-06-02 00:37:47,484:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/gmap_dust90_2048.fits
2023-06-02 00:39:11,339:WARNING:pysm3:No physical unit associated with file /mnt/sdceph/users/azonca/pysm-data/co/gmap_dust90_2048.fits
2023-06-02 00:39:11,340:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/mcmoleCO_HGL_2048.fits
2023-06-02 00:39:11,340:INFO:pysm3:Access data from /mnt/sdceph/users/azonca/pysm-data/co/mcmoleCO_HGL_2048.fits
2023-06-02 00:39:13,781:INFO:mapsims:Processing channel Channel CHLAT_f280
2023-06-02 00:39:13,782:INFO:mapsims:Bandpass integration for Channel CHLAT_f280
2023-06-02 00:39:14,944:INFO:mapsims:Smoothing and coord-transform for Channel CHLAT_f280
/mnt/home/azonca/mambaforge-pypy3/envs/so/lib/python3.10/site-packages/healpy/sphtfunc.py:414: RuntimeWarning: invalid value encountered in double_scalars
  return realalm2alm(res[0]), res[3] / norm(maps.reshape((-1,))), res[2]
2023-06-02 00:39:24,761:INFO:pysm3:Used map2alm_lsq, converged in 0 iterations,residual relative error nan
2023-06-02 00:39:24,761:INFO:pysm3:Smoothing with fwhm of 0.83 arcmin
2023-06-02 00:39:25,691:INFO:pysm3:Rotate Alm
2023-06-02 00:40:42,868:INFO:pysm3:Alm to map HEALPix
2023-06-02 00:40:53,616:INFO:mapsims:Writing output map cmbs4_co_co3_uKCMB_LAT-CHLAT_f280_nside4096.fits
2023-06-02 00:40:53,616:INFO:mapsims:Replace NaN with UNSEEN
2023-06-02 00:40:54,320:INFO:mapsims:Reorder ring to nest
2023-06-02 00:41:10,495:INFO:mapsims:Writing output map

real	4m4.366s
user	64m43.519s
sys	0m46.151s
